window.RogueConfig = {
    perf: {
        // Keep text/UI readable in small windows before we allow scaling down.
        minReadableScale: 0.95,
        // Adaptive performance mode hysteresis thresholds.
        lowThreshold: 48,
        recoverThreshold: 54,
        sampleWindow: 1.2,
    },
    wave: {
        baseKills: 10,
        killsGrowth: 5,
        baseSpawnCd: 1.5,
        minSpawnCd: 0.3,
        spawnCdDecay: 0.92,
        hpScale: 1.22,
        speedScale: 1.07,
        damageScale: 1.10,
        restTime: 2.5,
        maxWave: 25,
    },
    bosses: {
        minibossName: "Shard Warden",
        bigbossName: "Iron Tyrant",
        bigbossNamesByWave: {
            10: "Iron Tyrant",
            20: "Abyss Colossus",
        },
        endbossName: "The Null Sovereign",
    },
    skinShop: { // Only Fallback 
        skins: [
            { id: "default", name: "Classic Cyan", player: "#33ccff", glow: "rgba(51,204,255,0.25)", cost: 0, asset: "assets/playerskins/default.png" },
            { id: "surge", name: "Lime Surge", player: "#66ff99", glow: "rgba(102,255,153,0.25)", cost: 140, asset: "assets/playerskins/surge.png" },
            { id: "ember", name: "Ember Pulse", player: "#ff6688", glow: "rgba(255,102,136,0.25)", cost: 140, asset: "assets/playerskins/ember.png" },
            { id: "nova", name: "Nova Gold", player: "#ffd166", glow: "rgba(255,209,102,0.28)", cost: 180, asset: "assets/playerskins/nova.png" },
            { id: "rainbow", name: "Rainbow", player: "#ff00ff", glow: "rgba(255,0,255,0.4)", cost: 200, asset: "assets/playerskins/rainbow.png" },
            { id: "spiderman", name: "Spiderman Skin", player: "#d32f2f", glow: "rgba(30,90,200,0.35)", cost: 240, asset: "assets/playerskins/SpidermanSkin.png" },
        ],
        featuredIds: ["rainbow", "nova", "spiderman"],
    },
    upgrades: {
        rarityBaseWeights: {
            common: 100,
            rare: 16,
            epic: 5,
        },
        rarityColors: {
            common: "#cfd9e6",
            rare: "#66ddff",
            epic: "#c38bff",
        },
        epicUnlockWave: 6,
        waveBoosts: [
            { wave: 8, rare: 1.35, epic: 1.5 },
            { wave: 15, rare: 1.7, epic: 2.2 },
            { wave: 20, rare: 2.1, epic: 3.0 },
        ],
        bonusWaveBoost: {
            rare: 1.25,
            epic: 1.4,
        },
        bigbossBoost: {
            rare: 1.2,
            epic: 1.35,
        },
        tuning: {
            damage1: 5,
            damage2: 10,
            moveSpeedMult1: 1.15,
            moveSpeedMult2: 1.25,
            fireRateMult1: 0.8,
            fireRateMult2: 0.65,
            maxHp1: 25,
            maxHp2: 50,
            healPercent: 0.3,
            xpMagnetRange: 40,
            armor1: 3,
            armor2: 6,
            hpRegen1: 2,
            hpRegen2: 5,
            piercing: 1,
            multiShot: 1,
            critChanceAdd: 0.1,
            critDamageAdd: 0.5,
            bulletSizeMult: 1.3,
            rangeMult1: 1.2,
            rangeMult2: 1.4,
            xpGainMult1: 1.25,
            xpGainMult2: 1.5,
            executeAdd1: 0.08,
            executeAdd2: 0.12,
            executeCap: 0.5,
            weaponLevelAdd: 1,
        },
    },
    prestige: {
        enabled: true,
        gainPerClear: 1,
        resetShards: true,
        resetMeta: true,
        skinThresholds: [
            { prestigeLevel: 1, skinId: "prestige_bronze" },
            { prestigeLevel: 2, skinId: "prestige_silver" },
            { prestigeLevel: 3, skinId: "prestige_gold" },
            { prestigeLevel: 5, skinId: "prestige_diamond" },
            { prestigeLevel: 7, skinId: "prestige_platinum" },
            { prestigeLevel: 10, skinId: "prestige_emerald" },
        ],
    },
};
