name: Build and Deploy to Itch
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # This creates your zip file
      - name: Zip Web Files
        run: zip -r web-build.zip ./ -x "*.git*" ".github/*"

      # Using the ManleyJster action which is currently the most stable
      - name: Upload to Itch.io
        uses: manleyjster/action-itch.io@v1.1.0
        with:
          # Note the slight name changes in these variables
          butler_key: ${{ secrets.BUTLER_API_KEY }}
          itch_user: LennyXD
          itch_game: roguewave
          package: web-build.zip
          channel: html5
